"""Notification event constants (not DB rows)."""

USER_REGISTERED = 'USER_REGISTERED'
EMAIL_VERIFICATION_REQUIRED = 'EMAIL_VERIFICATION_REQUIRED'
MOBILE_VERIFICATION_REQUIRED = 'MOBILE_VERIFICATION_REQUIRED'
PASSWORD_RESET_REQUESTED = 'PASSWORD_RESET_REQUESTED'
PASSWORD_CHANGED = 'PASSWORD_CHANGED'
LOGIN_OTP_REQUESTED = 'LOGIN_OTP_REQUESTED'
ORDER_CREATED = 'ORDER_CREATED'
ORDER_CONFIRMED = 'ORDER_CONFIRMED'
ORDER_CANCELLED = 'ORDER_CANCELLED'
ORDER_STATUS_CHANGED = 'ORDER_STATUS_CHANGED'
PAYMENT_INITIATED = 'PAYMENT_INITIATED'
PAYMENT_SUCCESS = 'PAYMENT_SUCCESS'
PAYMENT_FAILED = 'PAYMENT_FAILED'
PAYMENT_CANCELLED = 'PAYMENT_CANCELLED'
REFUND_REQUESTED = 'REFUND_REQUESTED'
REFUND_PROCESSING = 'REFUND_PROCESSING'
REFUND_COMPLETED = 'REFUND_COMPLETED'
REFUND_FAILED = 'REFUND_FAILED'
DELIVERY_ASSIGNED = 'DELIVERY_ASSIGNED'
ORDER_READY_FOR_DELIVERY = 'ORDER_READY_FOR_DELIVERY'
ORDER_OUT_FOR_DELIVERY = 'ORDER_OUT_FOR_DELIVERY'
DELIVERY_COMPLETED = 'DELIVERY_COMPLETED'
REVIEW_SUBMITTED = 'REVIEW_SUBMITTED'
REVIEW_APPROVED = 'REVIEW_APPROVED'
REVIEW_REJECTED = 'REVIEW_REJECTED'
NEW_ORDER = 'NEW_ORDER'
LOW_STOCK = 'LOW_STOCK'
ADMIN_PAYMENT_FAILED = 'ADMIN_PAYMENT_FAILED'
ADMIN_REFUND_FAILED = 'ADMIN_REFUND_FAILED'

ALL_EVENTS = [
    USER_REGISTERED,
    EMAIL_VERIFICATION_REQUIRED,
    MOBILE_VERIFICATION_REQUIRED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_CHANGED,
    LOGIN_OTP_REQUESTED,
    ORDER_CREATED,
    ORDER_CONFIRMED,
    ORDER_CANCELLED,
    ORDER_STATUS_CHANGED,
    PAYMENT_INITIATED,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    PAYMENT_CANCELLED,
    REFUND_REQUESTED,
    REFUND_PROCESSING,
    REFUND_COMPLETED,
    REFUND_FAILED,
    DELIVERY_ASSIGNED,
    ORDER_READY_FOR_DELIVERY,
    ORDER_OUT_FOR_DELIVERY,
    DELIVERY_COMPLETED,
    REVIEW_SUBMITTED,
    REVIEW_APPROVED,
    REVIEW_REJECTED,
    NEW_ORDER,
    LOW_STOCK,
    ADMIN_PAYMENT_FAILED,
    ADMIN_REFUND_FAILED,
]

CRITICAL_EVENTS = frozenset({
    EMAIL_VERIFICATION_REQUIRED,
    MOBILE_VERIFICATION_REQUIRED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_CHANGED,
    LOGIN_OTP_REQUESTED,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    ORDER_CONFIRMED,
})

ADMIN_EVENTS = frozenset({
    NEW_ORDER,
    LOW_STOCK,
    ADMIN_PAYMENT_FAILED,
    ADMIN_REFUND_FAILED,
    REVIEW_SUBMITTED,
})

CHANNEL_EMAIL = 'email'
CHANNEL_SMS = 'sms'
CHANNEL_WHATSAPP = 'whatsapp'
CHANNEL_IN_APP = 'in_app'

ALL_CHANNELS = [CHANNEL_EMAIL, CHANNEL_SMS, CHANNEL_WHATSAPP, CHANNEL_IN_APP]

STATUS_PENDING = 'pending'
STATUS_SENT = 'sent'
STATUS_FAILED = 'failed'
STATUS_SKIPPED = 'skipped'
