from django.urls import path

from .views import (
    AdminLoginView,
    AdminLogoutView,
    AdminProductDetailView,
    AdminProductListCreateView,
    AdminReportActivityView,
    AdminReportProductPerformanceView,
    AdminReportProductsView,
    AdminReportRevenueView,
    AdminReportReviewsView,
    AdminReportSummaryView,
    AdminReportUsersView,
    AdminOrderListView,
    OrderCheckoutView,
    OrderDetailView,
    OrderListView,
    ProductAssetUploadView,
    ProductDetailView,
    ProductListView,
    ProductReviewListView,
    ReviewDetailView,
)

urlpatterns = [
    path('admin/login/', AdminLoginView.as_view(), name='admin-login'),
    path('admin/logout/', AdminLogoutView.as_view(), name='admin-logout'),
    path('products/', ProductListView.as_view(), name='product-list'),
    path('products/<int:pk>/', ProductDetailView.as_view(), name='product-detail'),
    path('products/<int:product_id>/reviews/', ProductReviewListView.as_view(), name='product-reviews'),
    path('products/<int:product_id>/image/', ProductAssetUploadView.as_view(), name='product-image-upload'),
    path('products/<int:product_id>/3d-assets/', ProductAssetUploadView.as_view(), name='product-3d-assets'),
    path('admin/products/', AdminProductListCreateView.as_view(), name='admin-product-list-create'),
    path('admin/products/<int:pk>/', AdminProductDetailView.as_view(), name='admin-product-detail'),
    path('admin/reports/summary/', AdminReportSummaryView.as_view(), name='admin-report-summary'),
    path('admin/reports/users/', AdminReportUsersView.as_view(), name='admin-report-users'),
    path('admin/reports/products/', AdminReportProductsView.as_view(), name='admin-report-products'),
    path('admin/reports/revenue/', AdminReportRevenueView.as_view(), name='admin-report-revenue'),
    path('admin/reports/reviews/', AdminReportReviewsView.as_view(), name='admin-report-reviews'),
    path('admin/reports/product-performance/', AdminReportProductPerformanceView.as_view(), name='admin-report-product-performance'),
    path('admin/reports/admin-activity/', AdminReportActivityView.as_view(), name='admin-report-activity'),
    path('reviews/<int:review_id>/', ReviewDetailView.as_view(), name='review-detail'),
    path('orders/checkout/', OrderCheckoutView.as_view(), name='order-checkout'),
    path('orders/', OrderListView.as_view(), name='order-list'),
    path('orders/<int:order_id>/', OrderDetailView.as_view(), name='order-detail'),
    path('admin/orders/', AdminOrderListView.as_view(), name='admin-order-list'),
]
