from django.urls import path

from .views import (
    AdminAssignDeliveryView,
    AdminLoginView,
    AdminLogoutView,
    AdminOrderListView,
    AdminOrderStatusUpdateView,
    AdminProductDetailView,
    AdminProductListCreateView,
    AdminReportActivityView,
    AdminReportProductPerformanceView,
    AdminReportProductsView,
    AdminReportRevenueView,
    AdminReportReviewsView,
    AdminReportSummaryView,
    AdminReportUsersView,
    AdminReviewApproveView,
    AdminReviewDetailView,
    AdminReviewListView,
    AdminReviewRejectView,
    DeliveryLocationUpdateView,
    EmployeeManagementView,
    OrderCheckoutView,
    OrderDetailView,
    OrderListView,
    OrderPaymentListView,
    OrderTrackingView,
    PaymentCreateView,
    PaymentDetailView,
    PaymentVerifyView,
    PaymentWebhookView,
    ProductAssetUploadView,
    ProductDetailView,
    ProductListView,
    ProductReviewListView,
    RetryPaymentView,
    ReviewDetailView,
)

urlpatterns = [
    path('admin/login/', AdminLoginView.as_view(), name='admin-login'),
    path('admin/logout/', AdminLogoutView.as_view(), name='admin-logout'),
    path('products/', ProductListView.as_view(), name='product-list'),
    path('products/<int:pk>/', ProductDetailView.as_view(), name='product-detail'),
    path('products/<int:product_id>/reviews/', ProductReviewListView.as_view(), name='product-reviews'),
    path('products/<int:product_id>/image/', ProductAssetUploadView.as_view(), name='product-image-upload'),
    path('products/<int:product_id>/3d-assets/', ProductAssetUploadView.as_view(), name='product-3d-assets'),
    path('admin/products/', AdminProductListCreateView.as_view(), name='admin-product-list-create'),
    path('admin/products/<int:pk>/', AdminProductDetailView.as_view(), name='admin-product-detail'),
    path('admin/reports/summary/', AdminReportSummaryView.as_view(), name='admin-report-summary'),
    path('admin/reports/users/', AdminReportUsersView.as_view(), name='admin-report-users'),
    path('admin/reports/products/', AdminReportProductsView.as_view(), name='admin-report-products'),
    path('admin/reports/revenue/', AdminReportRevenueView.as_view(), name='admin-report-revenue'),
    path('admin/reports/reviews/', AdminReportReviewsView.as_view(), name='admin-report-reviews'),
    path('admin/reports/product-performance/', AdminReportProductPerformanceView.as_view(), name='admin-report-product-performance'),
    path('admin/reports/admin-activity/', AdminReportActivityView.as_view(), name='admin-report-activity'),
    path('admin/reviews/', AdminReviewListView.as_view(), name='admin-review-list'),
    path('admin/reviews/<int:review_id>/', AdminReviewDetailView.as_view(), name='admin-review-detail'),
    path('admin/reviews/<int:review_id>/approve/', AdminReviewApproveView.as_view(), name='admin-review-approve'),
    path('admin/reviews/<int:review_id>/reject/', AdminReviewRejectView.as_view(), name='admin-review-reject'),
    path('reviews/<int:review_id>/', ReviewDetailView.as_view(), name='review-detail'),
    path('orders/checkout/', OrderCheckoutView.as_view(), name='order-checkout'),
    path('orders/', OrderListView.as_view(), name='order-list'),
    path('orders/<int:order_id>/', OrderDetailView.as_view(), name='order-detail'),
    path('orders/<int:order_id>/tracking/', OrderTrackingView.as_view(), name='order-tracking'),
    path('orders/<int:order_id>/location/', DeliveryLocationUpdateView.as_view(), name='order-location'),
    path('payments/create/', PaymentCreateView.as_view(), name='payment-create'),
    path('payments/verify/', PaymentVerifyView.as_view(), name='payment-verify'),
    path('payments/webhook/razorpay/', PaymentWebhookView.as_view(), name='payment-webhook-razorpay'),
    path('payments/<int:payment_id>/', PaymentDetailView.as_view(), name='payment-detail'),
    path('orders/<int:order_id>/payments/', OrderPaymentListView.as_view(), name='order-payment-list'),
    path('orders/<int:order_id>/retry-payment/', RetryPaymentView.as_view(), name='order-retry-payment'),
    path('admin/employees/', EmployeeManagementView.as_view(), name='admin-employee-list-create'),
    path('admin/employees/<int:employee_id>/', EmployeeManagementView.as_view(), name='admin-employee-detail'),
    path('admin/orders/', AdminOrderListView.as_view(), name='admin-order-list'),
    path('admin/orders/<int:order_id>/assign-delivery/', AdminAssignDeliveryView.as_view(), name='admin-assign-delivery'),
    path('admin/orders/<int:order_id>/status/', AdminOrderStatusUpdateView.as_view(), name='admin-order-status'),
]
