from django.urls import path

from .admin_ops import (
    AdminActiveDeliveriesView,
    AdminCustomerDetailView,
    AdminCustomerListView,
    AdminDashboardMetricsView,
    AdminExportView,
    AdminOrderDetailView,
    AdminSettingsStatusView,
    AdminUnassignDeliveryView,
)
from .views import (
    AdminAssignDeliveryView,
    AdminInventoryAdjustView,
    AdminInventoryDetailView,
    AdminInventoryHistoryView,
    AdminInventoryListView,
    AdminInventoryLowStockView,
    AdminLoginView,
    AdminLogoutView,
    AdminOrderCancelView,
    AdminOrderListView,
    AdminOrderRefundView,
    AdminOrderStatusUpdateView,
    AdminPaymentListView,
    AdminProductDetailView,
    AdminProductListCreateView,
    AdminRefundListView,
    AdminReportActivityView,
    AdminReportProductPerformanceView,
    AdminReportProductsView,
    AdminReportRevenueView,
    AdminReportReviewsView,
    AdminReportSummaryView,
    AdminReportUsersView,
    AdminReviewApproveView,
    AdminReviewDetailView,
    AdminReviewListView,
    AdminReviewRejectView,
    AdminCouponDetailView,
    AdminCouponListCreateView,
    AdminCouponRedemptionsView,
    CartValidateView,
    CouponValidateView,
    DeliveryLocationUpdateView,
    DeliveryQuoteView,
    AdminDeliveryZoneListCreateView,
    AdminDeliveryZoneDetailView,
    AdminDeliverySettingsView,
    EmployeeManagementView,
    EmployeeCategoryManagementView,
    EmployeeStatisticsView,
    OrderCancelView,
    OrderCheckoutView,
    OrderDetailView,
    OrderListView,
    OrderPaymentListView,
    OrderTrackingView,
    PaymentCreateView,
    PaymentDetailView,
    PaymentVerifyView,
    PaymentWebhookView,
    CategoryListView,
    ProductAssetUploadView,
    ProductDetailView,
    ProductSlugDetailView,
    ProductListView,
    ProductReviewListView,
    RetryPaymentView,
    ReviewDetailView,
)

urlpatterns = [
    path('admin/login/', AdminLoginView.as_view(), name='admin-login'),
    path('admin/logout/', AdminLogoutView.as_view(), name='admin-logout'),
    path('admin/dashboard/', AdminDashboardMetricsView.as_view(), name='admin-dashboard-metrics'),
    path('admin/settings/status/', AdminSettingsStatusView.as_view(), name='admin-settings-status'),
    path('admin/customers/', AdminCustomerListView.as_view(), name='admin-customer-list'),
    path('admin/customers/<int:user_id>/', AdminCustomerDetailView.as_view(), name='admin-customer-detail'),
    path('admin/orders/<int:order_id>/', AdminOrderDetailView.as_view(), name='admin-order-detail'),
    path('admin/orders/<int:order_id>/unassign-delivery/', AdminUnassignDeliveryView.as_view(), name='admin-unassign-delivery'),
    path('admin/deliveries/active/', AdminActiveDeliveriesView.as_view(), name='admin-active-deliveries'),
    path('admin/exports/<str:entity>/', AdminExportView.as_view(), name='admin-export'),
    path('categories/', CategoryListView.as_view(), name='category-list'),
    path('products/', ProductListView.as_view(), name='product-list'),
    path('products/<int:pk>/', ProductDetailView.as_view(), name='product-detail'),
    path('products/slug/<slug:slug>/', ProductSlugDetailView.as_view(), name='product-detail-slug'),
    path('products/<int:product_id>/reviews/', ProductReviewListView.as_view(), name='product-reviews'),
    path('products/<int:product_id>/image/', ProductAssetUploadView.as_view(), name='product-image-upload'),
    path('products/<int:product_id>/3d-assets/', ProductAssetUploadView.as_view(), name='product-3d-assets'),
    path('admin/products/', AdminProductListCreateView.as_view(), name='admin-product-list-create'),
    path('admin/products/<int:pk>/', AdminProductDetailView.as_view(), name='admin-product-detail'),
    path('admin/reports/summary/', AdminReportSummaryView.as_view(), name='admin-report-summary'),
    path('admin/reports/users/', AdminReportUsersView.as_view(), name='admin-report-users'),
    path('admin/reports/products/', AdminReportProductsView.as_view(), name='admin-report-products'),
    path('admin/reports/revenue/', AdminReportRevenueView.as_view(), name='admin-report-revenue'),
    path('admin/reports/reviews/', AdminReportReviewsView.as_view(), name='admin-report-reviews'),
    path('admin/reports/product-performance/', AdminReportProductPerformanceView.as_view(), name='admin-report-product-performance'),
    path('admin/reports/admin-activity/', AdminReportActivityView.as_view(), name='admin-report-activity'),
    path('admin/reviews/', AdminReviewListView.as_view(), name='admin-review-list'),
    path('admin/reviews/<int:review_id>/', AdminReviewDetailView.as_view(), name='admin-review-detail'),
    path('admin/reviews/<int:review_id>/approve/', AdminReviewApproveView.as_view(), name='admin-review-approve'),
    path('admin/reviews/<int:review_id>/reject/', AdminReviewRejectView.as_view(), name='admin-review-reject'),
    path('reviews/<int:review_id>/', ReviewDetailView.as_view(), name='review-detail'),
    path('orders/checkout/', OrderCheckoutView.as_view(), name='order-checkout'),
    path('orders/', OrderListView.as_view(), name='order-list'),
    path('orders/<int:order_id>/', OrderDetailView.as_view(), name='order-detail'),
    path('orders/<int:order_id>/cancel/', OrderCancelView.as_view(), name='order-cancel'),
    path('orders/<int:order_id>/tracking/', OrderTrackingView.as_view(), name='order-tracking'),
    path('orders/<int:order_id>/location/', DeliveryLocationUpdateView.as_view(), name='order-location'),
    path('payments/create/', PaymentCreateView.as_view(), name='payment-create'),
    path('payments/verify/', PaymentVerifyView.as_view(), name='payment-verify'),
    path('payments/webhook/razorpay/', PaymentWebhookView.as_view(), name='payment-webhook-razorpay'),
    path('payments/<int:payment_id>/', PaymentDetailView.as_view(), name='payment-detail'),
    path('orders/<int:order_id>/payments/', OrderPaymentListView.as_view(), name='order-payment-list'),
    path('orders/<int:order_id>/retry-payment/', RetryPaymentView.as_view(), name='order-retry-payment'),
    path('admin/employees/', EmployeeManagementView.as_view(), name='admin-employee-list-create'),
    path('admin/employees/stats/', EmployeeStatisticsView.as_view(), name='admin-employee-stats'),
    path('admin/employees/<int:employee_id>/', EmployeeManagementView.as_view(), name='admin-employee-detail'),
    path('admin/employee-categories/', EmployeeCategoryManagementView.as_view(), name='admin-employee-category-list-create'),
    path('admin/employee-categories/<int:category_id>/', EmployeeCategoryManagementView.as_view(), name='admin-employee-category-detail'),
    path('admin/orders/', AdminOrderListView.as_view(), name='admin-order-list'),
    path('admin/payments/', AdminPaymentListView.as_view(), name='admin-payment-list'),
    path('admin/orders/<int:order_id>/assign-delivery/', AdminAssignDeliveryView.as_view(), name='admin-assign-delivery'),
    path('admin/orders/<int:order_id>/status/', AdminOrderStatusUpdateView.as_view(), name='admin-order-status'),
    path('admin/orders/<int:order_id>/cancel/', AdminOrderCancelView.as_view(), name='admin-order-cancel'),
    path('admin/orders/<int:order_id>/refund/', AdminOrderRefundView.as_view(), name='admin-order-refund'),
    path('admin/refunds/', AdminRefundListView.as_view(), name='admin-refund-list'),
    path('cart/validate/', CartValidateView.as_view(), name='cart-validate'),
    path('coupons/validate/', CouponValidateView.as_view(), name='coupon-validate'),
    path('admin/coupons/', AdminCouponListCreateView.as_view(), name='admin-coupon-list-create'),
    path('admin/coupons/<int:coupon_id>/', AdminCouponDetailView.as_view(), name='admin-coupon-detail'),
    path('admin/coupons/<int:coupon_id>/redemptions/', AdminCouponRedemptionsView.as_view(), name='admin-coupon-redemptions'),
    path('admin/inventory/', AdminInventoryListView.as_view(), name='admin-inventory-list'),
    path('admin/inventory/low-stock/', AdminInventoryLowStockView.as_view(), name='admin-inventory-low-stock'),
    path('admin/inventory/<int:product_id>/', AdminInventoryDetailView.as_view(), name='admin-inventory-detail'),
    path('admin/inventory/<int:product_id>/adjust/', AdminInventoryAdjustView.as_view(), name='admin-inventory-adjust'),
    path('admin/inventory/<int:product_id>/history/', AdminInventoryHistoryView.as_view(), name='admin-inventory-history'),
    path('delivery/quote/', DeliveryQuoteView.as_view(), name='delivery-quote'),
    path('admin/delivery-zones/', AdminDeliveryZoneListCreateView.as_view(), name='admin-delivery-zone-list'),
    path('admin/delivery-zones/<int:zone_id>/', AdminDeliveryZoneDetailView.as_view(), name='admin-delivery-zone-detail'),
    path('admin/delivery-settings/', AdminDeliverySettingsView.as_view(), name='admin-delivery-settings'),
]
