# Generated by Django 5.2.17 on 2026-09-27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, default='', max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_views', to='catalog.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('product_create', 'Product Created'), ('product_update', 'Product Updated'), ('product_delete', 'Product Deleted'), ('product_image_upload', 'Product Image Upload'), ('product_3d_upload', '3D Asset Upload'), ('review_moderate', 'Review Moderated'), ('settings_update', 'Settings Updated')], default='login', max_length=40)),
                ('entity_type', models.CharField(blank=True, default='', max_length=40)),
                ('entity_id', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='productview',
            index=models.Index(fields=['product', 'created_at'], name='catalog_prod_product__86a2dd_idx'),
        ),
        migrations.AddIndex(
            model_name='productview',
            index=models.Index(fields=['user', 'created_at'], name='catalog_prod_user_id_5bd7f2_idx'),
        ),
        migrations.AddIndex(
            model_name='adminactivity',
            index=models.Index(fields=['admin_user', 'created_at'], name='catalog_adm_admin_us_8d1775_idx'),
        ),
        migrations.AddIndex(
            model_name='adminactivity',
            index=models.Index(fields=['action', 'created_at'], name='catalog_adm_action_9591ce_idx'),
        ),
        migrations.AddIndex(
            model_name='adminactivity',
            index=models.Index(fields=['entity_type', 'entity_id'], name='catalog_adm_entity_t_08a7fb_idx'),
        ),
    ]
