# Generated by Django 5.2.16 on 2026-09-27 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_adminactivity_productview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=40, unique=True)),
                ('customer_name', models.CharField(max_length=120)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_mobile', models.CharField(max_length=20)),
                ('shipping_address', models.CharField(max_length=255)),
                ('shipping_address_2', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=80)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=80)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=160)),
                ('product_image', models.URLField(blank=True, default='')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='adminactivity',
            new_name='catalog_adm_admin_u_4b017b_idx',
            old_name='catalog_adm_admin_us_8d1775_idx',
        ),
        migrations.RenameIndex(
            model_name='adminactivity',
            new_name='catalog_adm_action_6325dc_idx',
            old_name='catalog_adm_action_9591ce_idx',
        ),
        migrations.RenameIndex(
            model_name='adminactivity',
            new_name='catalog_adm_entity__b7f785_idx',
            old_name='catalog_adm_entity_t_08a7fb_idx',
        ),
        migrations.RenameIndex(
            model_name='productview',
            new_name='catalog_pro_product_afc182_idx',
            old_name='catalog_prod_product__86a2dd_idx',
        ),
        migrations.RenameIndex(
            model_name='productview',
            new_name='catalog_pro_user_id_c33cb6_idx',
            old_name='catalog_prod_user_id_5bd7f2_idx',
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product', 'status', 'created_at'], name='catalog_rev_product_f8b28a_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating', 'status'], name='catalog_rev_rating_12df31_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['created_at'], name='catalog_rev_created_05b149_idx'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.product'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'created_at'], name='catalog_ord_user_id_14c878_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='catalog_ord_status_aff486_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='catalog_ord_order_n_5ffbc2_idx'),
        ),
    ]
