# Generated by Django 5.2.16 on 2026-09-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_inventory_stock'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='inventorytransaction',
            new_name='catalog_inv_product_c36c30_idx',
            old_name='catalog_inv_product_0c3a2a_idx',
        ),
        migrations.RenameIndex(
            model_name='inventorytransaction',
            new_name='catalog_inv_referen_01022b_idx',
            old_name='catalog_inv_referen_7e1c4b_idx',
        ),
        migrations.RenameIndex(
            model_name='inventorytransaction',
            new_name='catalog_inv_adjustm_131bdc_idx',
            old_name='catalog_inv_adjustm_9a2f1d_idx',
        ),
        migrations.AlterField(
            model_name='adminactivity',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('product_create', 'Product Created'), ('product_update', 'Product Updated'), ('product_delete', 'Product Deleted'), ('product_image_upload', 'Product Image Upload'), ('product_3d_upload', '3D Asset Upload'), ('review_moderate', 'Review Moderated'), ('settings_update', 'Settings Updated')], default='login', max_length=40),
        ),
    ]
