# Generated by Django 5.2.16 on 2026-09-28 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customer_address_delivery'),
        ('catalog', '0010_coupon_promo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_enabled', models.BooleanField(default=True)),
                ('default_delivery_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('free_delivery_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bakery_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('bakery_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('max_delivery_radius_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('per_km_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Delivery settings',
                'verbose_name_plural': 'Delivery settings',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.customeraddress'),
        ),
        migrations.AddField(
            model_name='order',
            name='landmark',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('postal_codes', models.JSONField(blank=True, default=list)),
                ('city', models.CharField(blank=True, default='', max_length=80)),
                ('state', models.CharField(blank=True, default='', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('free_delivery_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('eta_min_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('eta_max_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'name'], name='catalog_del_is_acti_89e8b2_idx')],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='catalog.deliveryzone'),
        ),
    ]
