# Generated by Django 5.2.16 on 2026-10-08 14:47

import django.db.models.deletion
from django.db import migrations, models


def seed_employee_categories(apps, schema_editor):
    Employee = apps.get_model('catalog', 'Employee')
    EmployeeCategory = apps.get_model('catalog', 'EmployeeCategory')
    category_names = [
        'Accountant',
        'Front Desk',
        'Sweeper',
        'Chef',
        'Baker',
        'Delivery Staff',
        'Manager',
        'Sales Staff',
        'Customer Support',
        'Store/Inventory Staff',
        'Other',
    ]
    categories = {
        name: EmployeeCategory.objects.using(schema_editor.connection.alias).get_or_create(name=name)[0]
        for name in category_names
    }
    Employee.objects.using(schema_editor.connection.alias).filter(category__isnull=True).update(
        category=categories['Delivery Staff'],
    )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_product_perf_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'employee categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='employment_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ON_LEAVE', 'On Leave'), ('TERMINATED', 'Terminated')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='adminactivity',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('product_create', 'Product Created'), ('product_update', 'Product Updated'), ('product_delete', 'Product Deleted'), ('product_image_upload', 'Product Image Upload'), ('product_3d_upload', '3D Asset Upload'), ('review_moderate', 'Review Moderated'), ('settings_update', 'Settings Updated'), ('order_status', 'Order Status Updated'), ('order_cancel', 'Order Cancelled'), ('refund', 'Refund Action'), ('inventory_adjust', 'Inventory Adjusted'), ('coupon_create', 'Coupon Created'), ('coupon_update', 'Coupon Updated'), ('employee_assign', 'Delivery Employee Assigned'), ('employee_unassign', 'Delivery Employee Unassigned'), ('employee_create', 'Employee Created'), ('employee_update', 'Employee Updated'), ('employee_deactivate', 'Employee Deactivated'), ('employee_category_create', 'Employee Category Created'), ('employee_category_update', 'Employee Category Updated'), ('customer_status', 'Customer Account Status'), ('export', 'Data Export')], default='login', max_length=40),
        ),
        migrations.AddField(
            model_name='employee',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='catalog.employeecategory'),
        ),
        migrations.RunPython(seed_employee_categories, migrations.RunPython.noop),
    ]
