"""
Django settings for pinkbakes_backend project.

Generated by 'django-admin startproject' using Django 5.2.17.
Security-sensitive values come from environment variables. Local defaults keep
DEBUG on for development; production must set DJANGO_DEBUG=false and secrets.
"""

import os
import sys
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

BASE_DIR = Path(__file__).resolve().parent.parent


def _env_bool(name, default=False):
    raw = os.environ.get(name)
    if raw is None:
        return default
    return str(raw).strip().lower() in ('1', 'true', 'yes', 'on')


def _env_list(name, default):
    raw = os.environ.get(name)
    if raw is None or not str(raw).strip():
        return list(default)
    return [part.strip() for part in str(raw).split(',') if part.strip()]


FRONTEND_URL = os.environ.get('FRONTEND_URL', 'https://pinkbakes.com')
PUBLIC_SITE_URL = os.environ.get('PUBLIC_SITE_URL', FRONTEND_URL)
PUBLIC_CONTACT_PHONE = os.environ.get('PUBLIC_CONTACT_PHONE', '6033430700')
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = _env_bool('EMAIL_USE_TLS', True)
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'pinkbakes@pinkbakes.com')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'pinkbakes@pinkbakes.com')
SERVER_EMAIL = DEFAULT_FROM_EMAIL

PAYMENT_GATEWAY = os.environ.get('PAYMENT_GATEWAY', 'razorpay')
PAYMENT_ENABLED = _env_bool('PAYMENT_ENABLED', False)
# Empty defaults outside DEBUG so production never silently uses placeholder secrets.
_DEBUG_EARLY = _env_bool('DJANGO_DEBUG', True)
RAZORPAY_KEY_ID = os.environ.get(
    'RAZORPAY_KEY_ID',
    'rzp_test_default_key' if _DEBUG_EARLY else '',
)
RAZORPAY_KEY_SECRET = os.environ.get(
    'RAZORPAY_KEY_SECRET',
    'test_razorpay_secret' if _DEBUG_EARLY else '',
)
RAZORPAY_WEBHOOK_SECRET = os.environ.get(
    'RAZORPAY_WEBHOOK_SECRET',
    'test_webhook_secret' if _DEBUG_EARLY else '',
)
RAZORPAY_CURRENCY = os.environ.get('RAZORPAY_CURRENCY', 'INR')
DEFAULT_LOW_STOCK_THRESHOLD = int(os.environ.get('DEFAULT_LOW_STOCK_THRESHOLD', '5') or 5)

if EMAIL_HOST:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# SECURITY: DEBUG defaults True for local; production must set DJANGO_DEBUG=false.
DEBUG = _DEBUG_EARLY

SECRET_KEY = (os.environ.get('DJANGO_SECRET_KEY') or '').strip()
if not SECRET_KEY:
    if DEBUG:
        # Dev-only placeholder. Never deploy with DEBUG=true.
        SECRET_KEY = 'django-insecure-dev-only-set-DJANGO_SECRET_KEY-before-production'
    else:
        raise ImproperlyConfigured(
            'DJANGO_SECRET_KEY environment variable is required when DJANGO_DEBUG=false.'
        )

ALLOWED_HOSTS = _env_list('DJANGO_ALLOWED_HOSTS', ['localhost', '127.0.0.1'] if not DEBUG else ['*'])

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'accounts',
    'catalog.apps.CatalogConfig',
    'notifications',
    'seo',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pinkbakes_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pinkbakes_backend.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'

REST_FRAMEWORK = {

    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': os.environ.get('THROTTLE_ANON', '240/hour'),
        'user': os.environ.get('THROTTLE_USER', '2000/hour'),
        'auth': os.environ.get('THROTTLE_AUTH', '20/minute'),
        'otp': os.environ.get('THROTTLE_OTP', '8/minute'),
        'payment': os.environ.get('THROTTLE_PAYMENT', '30/minute'),
        'admin_login': os.environ.get('THROTTLE_ADMIN_LOGIN', '10/minute'),
    },
}

CORS_ALLOWED_ORIGINS = _env_list(
    'CORS_ALLOWED_ORIGINS',
    [
        'http://localhost:5173',
        'http://127.0.0.1:5173',
        'https://pinkbakes.com',
        'https://www.pinkbakes.com',
    ],
)
CORS_ALLOW_CREDENTIALS = _env_bool('CORS_ALLOW_CREDENTIALS', False)

CSRF_TRUSTED_ORIGINS = _env_list(
    'CSRF_TRUSTED_ORIGINS',
    [
        'http://localhost:5173',
        'http://127.0.0.1:5173',
        'https://pinkbakes.com',
        'https://www.pinkbakes.com',
    ],
)

# Production HTTPS / browser hardening (off in DEBUG so local HTTP keeps working).
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_REFERRER_POLICY = 'same-origin'
if not DEBUG:
    SECURE_SSL_REDIRECT = _env_bool('SECURE_SSL_REDIRECT', True)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = True
    SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '31536000') or 0)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', True)
    SECURE_HSTS_PRELOAD = _env_bool('SECURE_HSTS_PRELOAD', False)
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

COUPON_RESTORE_ON_CANCEL = _env_bool('COUPON_RESTORE_ON_CANCEL', False)

NOTIFICATION_EMAIL_ENABLED = _env_bool('NOTIFICATION_EMAIL_ENABLED', True)
SMS_PROVIDER = os.environ.get('SMS_PROVIDER', '')
TWILIO_ACCOUNT_SID = os.environ.get('TWILIO_ACCOUNT_SID', '')
TWILIO_AUTH_TOKEN = os.environ.get('TWILIO_AUTH_TOKEN', '')
TWILIO_FROM_NUMBER = os.environ.get('TWILIO_FROM_NUMBER', '')
WHATSAPP_API_URL = os.environ.get('WHATSAPP_API_URL', '')
WHATSAPP_TOKEN = os.environ.get('WHATSAPP_TOKEN', '')
WHATSAPP_PHONE_NUMBER_ID = os.environ.get('WHATSAPP_PHONE_NUMBER_ID', '')


# LocMem cache for short-TTL public catalog + admin overview KPIs.
# See catalog.cache_utils for keys/TTLs/invalidation. No Redis required.
# Do NOT store payment/order/inventory/coupon/auth secrets here.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'pinkbakes-default',
        'TIMEOUT': 60,
        'OPTIONS': {'MAX_ENTRIES': 2000},
    }
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Cap uploaded body size (admin asset URL posts are small; guards multipart abuse).
DATA_UPLOAD_MAX_MEMORY_SIZE = int(os.environ.get('DATA_UPLOAD_MAX_MEMORY_SIZE', str(2 * 1024 * 1024)))
FILE_UPLOAD_MAX_MEMORY_SIZE = int(os.environ.get('FILE_UPLOAD_MAX_MEMORY_SIZE', str(2 * 1024 * 1024)))

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'sensitive_scrub': {
            '()': 'pinkbakes_backend.logging_filters.SensitiveDataFilter',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'filters': ['sensitive_scrub'],
        },
    },
    'root': {
        'handlers': ['console'],
        'level': os.environ.get('LOG_LEVEL', 'INFO'),
    },
}


# Relax throttles during manage.py test so suite payment/auth calls do not 429.
if "test" in sys.argv:
    REST_FRAMEWORK["DEFAULT_THROTTLE_RATES"] = {
        "anon": "100000/minute",
        "user": "100000/minute",
        "auth": "100000/minute",
        "otp": "100000/minute",
        "payment": "100000/minute",
        "admin_login": "100000/minute",
    }

